### ISSUE TITLE
Course header image issue

### ISSUE THREAD

**Issue by manishadayal** [manishadayal/maker#18]
The size of the header is good, but inside the actual courses in the area where we attach our image, the image on the staging site now is cut off and therefore the section needs to be expanded to allow more room. I have attached a screenshot of our current website (how we would like it) and the staging site. Please let us know if there is nothing you can do about that so we can see if maybe we should remove the logo to allow more room. 
![Screen Shot 2021-04-07 at 3 42 46 PM](https://user-images.githubusercontent.com/60266068/114021619-83444700-988e-11eb-80a3-04ad22cd2e42.jpg)
![Screen Shot 2021-04-07 at 3 48 36 PM](https://user-images.githubusercontent.com/60266068/114021645-89d2be80-988e-11eb-8f8d-3f4cc72506b5.jpg)

**Comment by Rohitsharma2019** [comment]
issue resolved #19
